language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - SYMFONY_VERSION=2.3.*

install:
    - composer self-update
    - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
    - composer require --no-update symfony/form:${SYMFONY_VERSION}
    - if [[ "$SYMFONY_VERSION" =~ ^2\.[2-6] ]]; then composer require --no-update --dev symfony/asset:2.7.*; else composer require --no-update --dev symfony/asset:${SYMFONY_VERSION}; fi
    - composer require --no-update --dev symfony/templating:${SYMFONY_VERSION}
    - composer require --no-update --dev symfony/twig-bridge:${SYMFONY_VERSION}
    - composer require --no-update --dev symfony/yaml:${SYMFONY_VERSION}
    - composer remove --no-update --dev friendsofphp/php-cs-fixer
    - if [[ "$SYMFONY_VERSION" = *dev* ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
    - composer update --prefer-source `if [[ $COMPOSER_PREFER_LOWEST = true ]]; then echo "--prefer-lowest --prefer-stable"; fi`

script: vendor/bin/phpunit --coverage-clover build/clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.2.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: SYMFONY_VERSION=2.3.*
        - php: 5.6
          env: SYMFONY_VERSION=2.4.*
        - php: 5.6
          env: SYMFONY_VERSION=2.5.*
        - php: 5.6
          env: SYMFONY_VERSION=2.6.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.1.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.2.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.3.*@dev SYMFONY_DEPRECATIONS_HELPER=strict
    allow_failures:
        - env: SYMFONY_VERSION=3.3.*@dev SYMFONY_DEPRECATIONS_HELPER=strict

notifications:
    email: geloen.eric@gmail.com
